import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, BarChart3, Bot, Check, ChevronDown, CircleDollarSign, FilePenLine, Menu, MessageSquareText, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { createElement, useState } from "react";

const faqs = [
  ["Does MASS AI post content automatically?", "No. MASS AI creates editable drafts and planning recommendations. You review, refine, and publish through your own channels."],
  ["Will the AI promise more revenue or customers?", "No. MASS AI focuses on practical recommendations and relevant metrics; it does not guarantee commercial outcomes."],
  ["Can I use my own performance data?", "Yes. The MVP accepts manually entered reach, engagement, clicks, leads, conversions, and spend, then separates raw data from AI interpretation."],
  ["How is the trial calculated?", "The 14-day trial period is calculated from your real account creation date. The product does not simulate subscription or payment data."],
];

const workflowSteps: Array<{ icon: any; title: string; copy: string }> = [
  { icon: Target, title: "Understand", copy: "Capture your business, audience, goal, offers, and channels." },
  { icon: MegaphoneIcon, title: "Plan", copy: "Shape a campaign with a clear objective, message, CTA, and success metrics." },
  { icon: FilePenLine, title: "Create", copy: "Generate content drafts that you can edit before saving." },
  { icon: BarChart3, title: "Measure", copy: "Record the actual performance data available to you." },
  { icon: Bot, title: "Learn", copy: "Ask MASS AI to interpret context and recommend a next action." },
];

const featureCards: Array<{ icon: any; title: string; copy: string }> = [
  { icon: MegaphoneIcon, title: "Campaign management", copy: "Create, edit, track, and change the status of campaigns from draft to completed." },
  { icon: Bot, title: "AI Marketing Manager", copy: "Ask a business-specific marketing question and receive a structured recommendation." },
  { icon: Sparkles, title: "AI Campaign Planner", copy: "Turn a goal, audience, budget, and duration into a reviewable campaign plan." },
  { icon: FilePenLine, title: "Content Studio", copy: "Generate captions, messages, ad copy, headlines, and CTAs, then edit before saving." },
  { icon: BarChart3, title: "Marketing insights", copy: "Store real observations and keep them visibly separate from AI interpretation." },
  { icon: ShieldCheck, title: "Grounded guidance", copy: "MASS AI labels unknowns and avoids fabricated business facts and performance outcomes." },
];

function Logo() { return <div className="flex items-center gap-2.5"><div className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-teal-300 via-cyan-300 to-blue-500 shadow-lg shadow-cyan-300/20"><span className="text-sm font-black tracking-[-0.15em] text-[#041927]">M</span></div><div><p className="text-sm font-black tracking-[-0.06em] text-[#071b2e]">MASS <span className="text-teal-600">AI</span></p><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-500">Marketing manager</p></div></div>; }
export default function Home() { const { isAuthenticated } = useAuth(); const [open, setOpen] = useState(false); const [faq, setFaq] = useState<number | null>(0); const enter = () => { if (isAuthenticated) window.location.assign("/app"); else startLogin(); }; return <div className="min-h-screen overflow-x-hidden bg-[#fbfdfd] text-slate-900"><header className="sticky top-0 z-40 border-b border-slate-200/70 bg-[#fbfdfd]/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm font-semibold text-slate-600 md:flex"><a href="#how-it-works" className="hover:text-teal-700">How it works</a><a href="#features" className="hover:text-teal-700">Features</a><a href="#pricing" className="hover:text-teal-700">Pricing</a><a href="#faq" className="hover:text-teal-700">FAQ</a></nav><div className="hidden md:block"><Button onClick={enter} className="bg-[#0f766e] hover:bg-[#0b625c]">{isAuthenticated ? "Open workspace" : "Start free trial"}<ArrowRight className="ml-1 h-4 w-4" /></Button></div><button className="rounded-lg p-2 md:hidden" onClick={() => setOpen(current => !current)} aria-label="Toggle menu">{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{open && <div className="border-t border-slate-100 px-5 py-4 md:hidden"><div className="grid gap-3 text-sm font-semibold text-slate-600"><a href="#how-it-works" onClick={() => setOpen(false)}>How it works</a><a href="#features" onClick={() => setOpen(false)}>Features</a><a href="#pricing" onClick={() => setOpen(false)}>Pricing</a><a href="#faq" onClick={() => setOpen(false)}>FAQ</a><Button onClick={enter} className="mt-2 bg-[#0f766e] hover:bg-[#0b625c]">{isAuthenticated ? "Open workspace" : "Start free trial"}</Button></div></div>}</header>
  <main><section className="relative isolate"><div className="absolute inset-x-0 top-0 -z-10 h-[520px] bg-[radial-gradient(ellipse_at_top_right,_#bdf5e5_0%,_rgba(251,253,253,0)_58%)]" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-28 lg:pt-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-teal-200 bg-teal-50 px-3 py-1.5 text-xs font-bold text-teal-800"><Sparkles className="h-3.5 w-3.5" />Built for small business marketing</div><h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.06] tracking-[-0.055em] text-[#071b2e] sm:text-5xl lg:text-6xl">Your AI Marketing Manager for <span className="text-teal-600">Small Business.</span></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-slate-600 sm:text-lg">Plan smarter campaigns, create better content, and understand your marketing performance without hiring a full marketing team.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" onClick={enter} className="bg-[#0f766e] px-6 hover:bg-[#0b625c]">{isAuthenticated ? "Open my workspace" : "Start your 14-day free trial"}<ArrowRight className="ml-1.5 h-4 w-4" /></Button><a href="#how-it-works"><Button size="lg" variant="outline" className="w-full border-slate-300 bg-white sm:w-auto">See how it works</Button></a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-slate-600">{["No invented performance data", "Editable AI-generated content", "Context-aware guidance"].map(item => <span className="flex items-center gap-1.5" key={item}><Check className="h-3.5 w-3.5 text-teal-600" />{item}</span>)}</div></div><HeroPreview /></div></section>
  <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 md:grid-cols-3 lg:px-8">{[["Marketing should not require a full department.", "Local businesses often manage customers, operations, and marketing at the same time."], ["More than a caption generator.", "MASS AI helps connect business context, campaign planning, content, measurement, and next steps."], ["Built around practical decisions.", "Clarify the goal, create a plan, act deliberately, measure real results, then learn what to do next."]].map(([title, copy], index) => <div key={title}><span className="text-xs font-black text-teal-600">0{index + 1}</span><h2 className="mt-3 text-lg font-bold text-[#071b2e]">{title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">{copy}</p></div>)}</div></section>
  <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">How MASS AI works</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#071b2e] sm:text-4xl">A complete loop for clearer marketing decisions.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-5">{workflowSteps.map((step, index) => <div className="relative rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" key={step.title}><span className="absolute right-4 top-4 text-xs font-black text-slate-200">0{index + 1}</span><div className="grid h-9 w-9 place-items-center rounded-xl bg-teal-50 text-teal-700">{createElement(step.icon, { className: "h-4 w-4" })}</div><h3 className="mt-5 font-bold text-[#071b2e]">{step.title}</h3><p className="mt-2 text-xs leading-relaxed text-slate-600">{step.copy}</p></div>)}</div></section>
  <section id="features" className="bg-[#071b2e] py-20 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-300">MASS AI capabilities</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">A marketing command center, not another generic chatbot.</h2></div><p className="max-w-sm text-sm leading-relaxed text-slate-300">Everything is organized around your marketing workflow, with your business profile providing the common context.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{featureCards.map(card => <article className="rounded-2xl border border-white/10 bg-white/[0.045] p-5" key={card.title}>{createElement(card.icon, { className: "h-5 w-5 text-teal-300" })}<h3 className="mt-5 font-bold">{card.title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-300">{card.copy}</p></article>)}</div></div></section>
  <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">An example of focused guidance</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#071b2e] sm:text-4xl">Recommendations should reflect the business at hand.</h2><p className="mt-5 text-sm leading-relaxed text-slate-600">MASS AI brings together your stored profile and campaign context. When information is missing, it says so rather than filling the gap with invented facts.</p><div className="mt-7 rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">EXAMPLE BUSINESS CONTEXT</p><p className="mt-2 text-sm font-semibold text-slate-800">Local bakery · Nearby families · Instagram + WhatsApp · Goal: attract weekend customers</p></div></div><div className="rounded-3xl bg-gradient-to-br from-teal-50 via-white to-cyan-50 p-5 sm:p-7"><div className="rounded-2xl bg-[#071b2e] p-5 text-white shadow-xl"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-teal-300/15 text-teal-300"><Sparkles className="h-4 w-4" /></span><p className="text-sm font-bold">MASS AI recommendation</p></div><p className="mt-5 text-lg font-semibold leading-relaxed">“Run a weekend limited-time offer for nearby customers. Promote it through Instagram and WhatsApp with a clear cutoff time, then monitor offer clicks and pre-orders.”</p><div className="mt-6 grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-3">{[["Why", "A short window can create urgency for a local offer."], ["How", "Use one clear offer, deadline, and simple response path."], ["Monitor", "Offer clicks, messages, and completed orders."]].map(([label, text]) => <div key={label}><p className="text-xs font-bold text-teal-300">{label}</p><p className="mt-1 text-xs leading-relaxed text-slate-300">{text}</p></div>)}</div></div></div></section>
  <section id="pricing" className="border-y border-slate-200 bg-white py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">Start with 14 days</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#071b2e] sm:text-4xl">Explore a better way to organize your marketing.</h2><p className="mt-4 text-sm leading-relaxed text-slate-600">Your trial begins from your account creation date. Payment and subscription tools are intentionally not configured in this MVP.</p></div><div className="mx-auto mt-10 max-w-md rounded-3xl border border-slate-200 bg-[#fbfdfd] p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-bold text-[#071b2e]">MASS AI access</p><p className="mt-1 text-sm text-slate-600">14-day free trial</p></div><CircleDollarSign className="h-5 w-5 text-teal-600" /></div><p className="mt-6 text-3xl font-bold tracking-tight">Pricing <span className="text-slate-400">coming soon</span></p><p className="mt-3 text-sm leading-relaxed text-slate-600">This product view intentionally leaves billing as a future integration rather than implying a live plan or payment status.</p><Button onClick={enter} className="mt-6 w-full bg-[#0f766e] hover:bg-[#0b625c]">Start free trial <ArrowRight className="ml-1 h-4 w-4" /></Button></div></div></section>
  <section id="faq" className="mx-auto max-w-3xl px-5 py-20"><p className="text-center text-xs font-black uppercase tracking-[0.16em] text-teal-700">FAQ</p><h2 className="mt-3 text-center text-3xl font-bold tracking-tight text-[#071b2e]">Clear expectations from the start.</h2><div className="mt-10 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white px-5">{faqs.map(([question, answer], index) => <div key={question}><button className="flex w-full items-center justify-between gap-4 py-5 text-left font-bold text-[#071b2e]" onClick={() => setFaq(current => current === index ? null : index)}>{question}<ChevronDown className={`h-4 w-4 shrink-0 text-slate-500 transition ${faq === index ? "rotate-180" : ""}`} /></button>{faq === index && <p className="pb-5 text-sm leading-relaxed text-slate-600">{answer}</p>}</div>)}</div></section>
  <section className="mx-5 mb-8 rounded-3xl bg-[#071b2e] px-6 py-12 text-center text-white sm:mx-8"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-300">Make marketing more manageable</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">Give your business one place to understand, plan, create, measure, and learn.</h2><Button size="lg" onClick={enter} className="mt-7 bg-teal-400 text-[#04202c] hover:bg-teal-300">{isAuthenticated ? "Open my workspace" : "Start your 14-day free trial"}<ArrowRight className="ml-1 h-4 w-4" /></Button></section></main>
  <footer className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 text-xs text-slate-500 sm:flex-row lg:px-8"><Logo /><p className="max-w-sm leading-relaxed">MASS AI is an AI-powered marketing management workspace for small businesses. Recommendations are guides, not guarantees of business outcomes.</p><p>© {new Date().getFullYear()} MASS AI</p></footer></div>; }
function HeroPreview() { return <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-3 -z-10 rounded-[34px] bg-gradient-to-br from-teal-200/70 to-blue-200/40 blur-2xl" /><div className="overflow-hidden rounded-[26px] border border-slate-200 bg-white p-3 shadow-2xl shadow-slate-300/55"><div className="flex items-center gap-1.5 border-b border-slate-100 px-2 pb-3"><span className="h-2 w-2 rounded-full bg-rose-300" /><span className="h-2 w-2 rounded-full bg-amber-300" /><span className="h-2 w-2 rounded-full bg-teal-300" /><div className="ml-3 h-4 w-28 rounded bg-slate-100" /></div><div className="grid grid-cols-[72px_1fr] gap-3 pt-3"><div className="rounded-xl bg-[#071b2e] p-2"><div className="mx-auto grid h-6 w-6 place-items-center rounded-md bg-teal-300 text-[10px] font-black text-[#071b2e]">M</div><div className="mt-4 space-y-2">{Array.from({ length: 5 }).map((_, index) => <div key={index} className={`mx-auto h-1.5 rounded-full ${index === 0 ? "w-9 bg-teal-300" : "w-7 bg-white/20"}`} />)}</div></div><div className="space-y-3 pr-1"><div className="flex justify-between"><div><div className="h-2.5 w-24 rounded bg-slate-800" /><div className="mt-2 h-1.5 w-40 rounded bg-slate-100" /></div><div className="h-6 w-16 rounded-md bg-teal-600" /></div><div className="grid grid-cols-3 gap-2">{["Active campaigns", "Measured data", "Trial days"].map((label, index) => <div className="rounded-lg border border-slate-100 p-2" key={label}><div className="h-1.5 w-8 rounded bg-slate-200" /><div className="mt-2 text-sm font-black text-slate-800">{index === 0 ? "02" : index === 1 ? "12" : "14"}</div><div className="mt-1 text-[6px] font-semibold text-slate-400">{label}</div></div>)}</div><div className="rounded-xl bg-[#071b2e] p-3"><div className="flex items-center gap-1.5"><Sparkles className="h-3 w-3 text-teal-300" /><span className="text-[8px] font-bold text-white">MASS AI guidance</span></div><div className="mt-3 space-y-1.5"><div className="h-1.5 w-full rounded bg-white/25" /><div className="h-1.5 w-4/5 rounded bg-white/25" /><div className="h-1.5 w-2/3 rounded bg-teal-300/70" /></div></div></div></div></div><div className="absolute -bottom-5 -left-4 rounded-xl border border-slate-200 bg-white px-3 py-2 shadow-lg"><p className="text-[9px] font-bold text-slate-500">NEXT ACTION</p><p className="mt-0.5 text-[11px] font-bold text-[#071b2e]">Plan your weekend offer</p></div></div>; }
function MegaphoneIcon(props: any) { return <MessageSquareText {...props} />; }
